"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("Cloud Center is separate from local Settings and exposes the complete community workflow", () => {
  const html = read("public/index.html"), cloud = read("public/cloud-connect.js"), css = read("public/cloud-connect.css");
  assert.match(html, /id="settingsBtn"/);
  assert.match(html, /id="cloudAccountBtn"/);
  assert.match(html, /id="shareCanvasBtn"/);
  assert.match(cloud, /\["widget", "Widgets"/);
  assert.match(cloud, /\["canvas", "Canvases"/);
  for (const sort of ["recommended", "newest", "downloads", "favorites"]) assert.match(cloud, new RegExp(`value:\"${sort}\"`));
  for (const removed of ["price_low", "price_high", "Free + paid", "Paid with credits", "Redeem ", "80% rewards"]) assert.doesNotMatch(cloud, new RegExp(removed));
  assert.match(cloud, /\/api\/cloud\/community\/\$\{encodeURIComponent\(itemId\)\}\/thumbnail/);
  assert.match(cloud, /async function apiImage/);
  assert.match(cloud, /x-penecho-session/);
  assert.match(cloud, /URL\.createObjectURL\(blob\)/);
  assert.doesNotMatch(cloud, /el\("img", \{ src:`\/api\/cloud\/community/);
  assert.doesNotMatch(cloud, /priceCredits|Credit price|field\("Pricing"/);
  assert.match(cloud, /Auto-fill with current AI/);
  assert.match(cloud, /there is no image upload step/);
  assert.match(cloud, /Every launch Craft is free/);
  assert.match(cloud, /Browse public ideas and their lineage/);
  assert.match(cloud, /Your Craft is now part of the public commons/);
  assert.match(cloud, /Take it further/);
  assert.match(cloud, /PUBLICATION_TERMS_VERSION = "2026-08-11"/);
  assert.match(cloud, /CC BY 4\.0/);
  assert.match(cloud, /embedded source under/);
  assert.match(cloud, /contributionNote/);
  assert.match(cloud, /parentItemId/);
  assert.match(cloud, /window\.PenEchoCommunityUI/);
  assert.match(cloud, /Cloud Projects/);
  assert.match(cloud, /Private cross-device work/);
  assert.match(cloud, /\/api\/cloud\/library/);
  assert.match(cloud, /Save current Canvas/);
  assert.match(cloud, /window\.PenEchoCloudProjects/);
  assert.match(cloud, /base-revision-required/);
  assert.match(css, /\.cloud-item-preview/);
  assert.match(css, /\.cloud-item-preview img:not\(\[src\]\)/);
  assert.match(css, /\.cloud-project-card/);
  assert.match(css, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(css, /overflow-wrap: anywhere/);
  assert.match(html, /Share to Community · Coming soon/);
  assert.doesNotMatch(html, /points-priced|Share for points|earn points/);
});

test("community artifacts have bounded WebP previews and import both Widgets and Canvases locally", () => {
  const app = read("public/app.js"), main = read("src/server/main.js");
  assert.match(app, /maximumBytes:4\*1024\*1024/);
  assert.match(app, /maximumBytes:768\*1024/);
  assert.match(app, /snapshotPreview\(2048,1365\)/);
  assert.match(app, /communityImagesForCanvas\(canvas, \.82\)/);
  assert.match(app, /communityThumbnail/);
  assert.match(app, /suggestMetadata:suggestCommunityMetadata/);
  assert.match(app, /async function importCommunityCanvasArtifact/);
  assert.match(app, /importCanvas:importCommunityCanvasArtifact/);
  assert.match(app, /communityOriginItemId/);
  assert.match(app, /penechoCommunity/);
  assert.match(app, /lineageForArtifact:communityLineageForArtifact/);
  assert.match(main, /PENECHO_CLOUD_ENV/);
  assert.match(main, /PENECHO_CLOUD_ORIGIN/);
  assert.match(main, /https:\/\/internaltest\.penecho\.ai/);
  assert.match(main, /https:\/\/penecho\.ai/);
  assert.match(app, /Free community plugins/);
  assert.doesNotMatch(app, /points-priced|Share for points|earn points/);
});
