"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("Cloud Center keeps projects local to the app and sends Explore to PenEcho Cloud", () => {
  const html = read("public/index.html"), cloud = read("public/cloud-connect.js"), css = read("public/cloud-connect.css"), main = read("src/server/main.js");
  assert.match(html, /id="settingsBtn"/);
  assert.match(html, /id="cloudAccountBtn"/);
  assert.match(html, /id="shareCanvasBtn"/);
  assert.match(cloud, /new URL\("\/community\.html", `\$\{cloudOrigin\(\)\}\/`\)/);
  assert.match(cloud, /target:"_blank", rel:"noopener"/);
  assert.match(cloud, /Browse public Crafts on PenEcho Cloud/);
  assert.doesNotMatch(cloud, /function communityPanel/);
  assert.doesNotMatch(cloud, /function itemCard/);
  assert.doesNotMatch(cloud, /cloud-community-grid/);
  assert.doesNotMatch(cloud, /\/api\/cloud\/community\?\$\{query\}/);
  for (const removed of ["price_low", "price_high", "Free + paid", "Paid with credits", "Redeem ", "80% rewards"]) assert.doesNotMatch(cloud, new RegExp(removed));
  assert.match(cloud, /x-penecho-session/);
  assert.doesNotMatch(cloud, /priceCredits|Credit price|field\("Pricing"/);
  assert.match(cloud, /Auto-fill with current AI/);
  assert.match(cloud, /no image upload/);
  assert.match(cloud, /Preserve this moment/);
  assert.match(cloud, /Your Craft is now part of the public commons/);
  assert.match(cloud, /Take it further/);
  assert.match(cloud, /PUBLICATION_TERMS_VERSION = "2026-08-12"/);
  assert.match(cloud, /CC BY-SA 4\.0/);
  assert.match(cloud, /embedded source under/);
  assert.match(cloud, /Public Craft ML License/);
  assert.match(cloud, /continuationPrompt/);
  assert.match(cloud, /contributionNote/);
  assert.match(cloud, /parentItemId/);
  assert.match(cloud, /window\.PenEchoCommunityUI/);
  assert.match(cloud, /Cloud Projects/);
  assert.match(cloud, /Private cross-device work/);
  assert.match(cloud, /\/api\/cloud\/library/);
  assert.match(cloud, /Save current Canvas/);
  assert.match(cloud, /window\.PenEchoCloudProjects/);
  assert.match(cloud, /base-revision-required/);
  assert.match(cloud, /startBrowserSignInWatch/);
  assert.match(cloud, /PenEcho will connect here automatically/);
  assert.match(cloud, /window\.open\("about:blank"/);
  assert.match(cloud, /popup\.location\.replace\(started\.authorizationUrl\)/);
  assert.match(cloud, /window\.open\(started\.authorizationUrl, "_blank", "noopener"\)/);
  assert.match(cloud, /externalOpened:desktopApp/);
  assert.match(cloud, /Open sign-in page/);
  assert.match(cloud, /document\.visibilityState === "visible"/);
  assert.match(cloud, /visibilitychange/);
  assert.match(cloud, /event\.origin !== location\.origin/);
  assert.match(main, /window\.location\.replace\("\/"\)/);
  assert.match(main, /desktopApp:process\.env\.PENECHO_DESKTOP_APP==="true"/);
  assert.match(css, /\.cloud-section-tab\[href\]/);
  assert.doesNotMatch(css, /\.cloud-item-preview/);
  assert.doesNotMatch(css, /\.cloud-community-grid/);
  assert.match(css, /\.cloud-project-card/);
  assert.match(css, /overflow-wrap: anywhere/);
  assert.match(html, /Share to Community · Coming soon/);
  assert.doesNotMatch(html, /points-priced|Share for points|earn points/);
});

test("community artifacts have bounded WebP previews and import both Widgets and Canvases locally", () => {
  const app = read("public/app.js"), main = read("src/server/main.js");
  assert.match(app, /maximumBytes:4\*1024\*1024/);
  assert.match(app, /maximumBytes:768\*1024/);
  assert.match(app, /snapshotPreview\(2048,1365\)/);
  assert.match(app, /communityImagesForCanvas\(canvas, \.82\)/);
  assert.match(app, /communityThumbnail/);
  assert.match(app, /suggestMetadata:suggestCommunityMetadata/);
  assert.match(app, /async function importCommunityCanvasArtifact/);
  assert.match(app, /importCanvas:importCommunityCanvasArtifact/);
  assert.match(app, /communityOriginItemId/);
  assert.match(app, /penechoCommunity/);
  assert.match(app, /lineageForArtifact:communityLineageForArtifact/);
  assert.match(app, /markPublishedOrigin:markPublishedCommunityOrigin/);
  assert.match(app, /communityOriginGeneration/);
  assert.match(app, /persistCurrentCanvasCommunityOrigin/);
  assert.match(main, /PENECHO_CLOUD_ENV/);
  assert.match(main, /PENECHO_CLOUD_ORIGIN/);
  assert.match(main, /https:\/\/internaltest\.penecho\.ai/);
  assert.match(main, /https:\/\/penecho\.ai/);
  assert.match(app, /Free community plugins/);
  assert.doesNotMatch(app, /points-priced|Share for points|earn points/);
});
