"use strict";

const { getAuthoringGuidance, CANVAS_RENDERING_ROUTING } = require("./authoring-guidance.js");

const INVOCATION_INSTRUCTIONS = `Use PenEcho for explicit visual-workspace requests naming penecho, echo, canvas or 画布, e.g. “echo一下这个想法”, “penecho一下文件夹的架构”, “把你要做的修改放到canvas”. Start with required title and stable client/sessionKey; omit instanceId/canvasId for the latest opted-in browser on a new conversation, or use penecho_list_canvases for an exact opted-in connection target. Ordinary shell echo commands and unrelated canvas mentions are not triggers.`;

const CANVAS_INPUT_INSTRUCTIONS = 'When the user refers to Canvas drawings, handwriting, circles, arrows or annotations (e.g. “请按照我画的内容来执行”, “请按照我写的来进行操作”, “follow what I drew/wrote”), decide whether the requested action depends on visual information missing from the available context. These phrases are routing cues, not mandatory screenshot triggers. Reuse already understood drawings, supplied images or readable feedback captures when sufficient; do not re-view or recapture unchanged content on every turn or edit. Ordinary source edits and fully specified text instructions need no image. If execution depends on unseen, changed or unclear ink or spatial relationships, inspect the relevant image; source/JSON alone cannot establish those visual details. Only when existing image evidence is insufficient, call penecho_capture_canvas with quality:"basic" and the relevant selection, region, object or viewport target; use target:"canvas" for whole-Canvas context. Request detail only if needed to read the marks. Use the intended document/session; never silently switch documents. If capture fails or handwriting is ambiguous, resolve that specific gap before dependent edits. Read source as needed for implementation.';

const WORKSPACE_INSTRUCTIONS = `${INVOCATION_INSTRUCTIONS} ${CANVAS_INPUT_INSTRUCTIONS} ${CANVAS_RENDERING_ROUTING} For “current canvas”, “this canvas”, “当前画布”, “这个画布” or selection edits, use penecho_start_session target:"current" without documentId. Retain documentId/sessionId; if bound elsewhere use a distinct stable attachment sessionKey and retain both handles. Read before edits. create_text: display-only omits region; annotations use evidence-based region (runtime/viewport.json). No baseRevision/width/height. draw_ink uses current baseRevision, explicit #RRGGBB color and world-unit points; preserve user work and Undo. Background ink requires intended show then reread revision. Retry requestId only with identical arguments. Never guess documents by title. Reuse client/sessionKey and sessionId/documentId across turns/reconnects. Old conversations restore their original document, even closed saved documents in the background. restore defaults true; only DOCUMENT_NOT_FOUND permits replacement. Permission/storage errors remain errors; restore:false disables replacement, show defaults false. Existing documents require binding or user intent. With a selected live Canvas, use it proactively for useful visuals; skip routine edits. Keep the first useful output fast. Reuse artifact IDs. Batch meaningful public findings/blockers/completion in penecho_update_session; no progress boards, per-tool updates or idle polling. Read inbox at work checkpoints and before yielding; acknowledge done/error for quick actions, received/working only for useful waits. PenEcho starts HTTPS; browsers opt in. The stdio CLI loads CA/credential, trying known IP:port, fresh shared cache, then one-shot discovery without config edits or a daemon. Idle releases HTTP after 30 minutes, retaining stdin. Failed idle reconnect retries fresh cache then discovery; no idle CLI exit. Relaunch belongs to the AI host and must be verified. Retain client/sessionKey/documentId across processes; a fresh process must start_session with that binding. Transport IDs/PIDs are not conversation identity. A stopped client is never auto-woken. Publish final status; never send private chain-of-thought, secrets or transcripts.`;

const PAGE_PREVIEW_INSTRUCTIONS = `For one page, keep one complete scrollable Widget and update the same artifactId. Different artifactIds create separate Canvas objects; supporting/alternative roles do not merge them. Create extra page variants or section Widgets only when the user asks to compare separate deliverables. Widget artifact captures include full rendered document content; viewport gives the actual Widget size and capture.contentSize/overflow report scrolling, including clipped nested scroll panels whose layout is preserved. A complete image does not mean everything fits onscreen. Use object/Canvas capture for actual visible layout, or intent:inspect with capture:true for an exact temporary viewport check; never deliver inspections as extra Widgets. A capture failure may leave the Widget applied: inspect the existing artifact and reuse its ID, never create a replacement ID to retry.`;

const WIDGET_VIEWPORT_INSTRUCTIONS = `New Widgets use the available unobscured viewport. Default/page takes its aspect ratio; explicit dimensions and other presets are preferred CSS content dimensions capped independently to available width and height, separate from Canvas world geometry. Read the returned actual viewport. Use width:100% and min-width:0 at the HTML root, responsive columns/media or container queries, normal readable CSS font sizes and vertical scrolling; never a fixed root pixel width or whole-page transform/zoom to squeeze content. Source updates preserve existing artifact geometry. intent:inspect keeps the exact requested viewport and creates no Canvas object.`;

const VISUAL_INSTRUCTIONS = `UI: deliver a usable page. ${PAGE_PREVIEW_INSTRUCTIONS} New Widgets use the available unobscured viewport. Default/page takes its aspect ratio; dimensions/presets are CSS preferences capped independently, not world geometry. intent:inspect keeps the exact requested viewport and creates no Canvas object. Source updates preserve existing artifact geometry. Never combine size with dimensions. Explanations use clear hierarchy and meaningful diagrams/tables. Reflow with readable type; never shrink the page, clip controls or invent data. Use labeled keyboard-accessible controls. Filters, tabs and toggles work locally without model calls; only explicit AI choices use data-penecho-action plus a bounded data-penecho-prompt. Label those as requests, not instant AI execution. Ordinarily use capture:false; UI review may combine capture:true at basic quality. Inspect returned pixels and fix concrete defects; stop once usable. On demand: penecho_get_guidance id visual-explorer for explanations; general-html for new UI, never auto-VE; math-2d/physics-2d/math-3d for science.`;

const VISUAL_TOOL_INSTRUCTIONS = `${PAGE_PREVIEW_INSTRUCTIONS} ${WIDGET_VIEWPORT_INSTRUCTIONS} Prefer this for UI design/review: use page for available-viewport UI, explicit preferred dimensions for mobile, and base only for one compact idea. Preserve product styling, readable type and responsive layout. Use labeled native controls with keyboard access; only explicit AI requests opt into data-penecho-action/data-penecho-prompt. Ordinary updates use capture:false; initial UI review or substantial layout changes may combine capture:true at basic quality. Read the image and fix concrete defects without recapturing unchanged work.`;

const MCP_PRESENTATION_INSTRUCTIONS = `${PAGE_PREVIEW_INSTRUCTIONS} Use presentation.intent explain|deliver|compare|review to state why an artifact is shown, and role primary|supporting|alternative to state its hierarchy. ${WIDGET_VIEWPORT_INSTRUCTIONS} Nominal size presets (exact for inspect and unchanged for plots) are base 480×360, wide 992×360, tall 480×752, large 992×752, and page 1200×800. Use relativeTo with a stable artifactId for below/beside placement; compare defaults beside. Review requests attention by default, while supporting or alternative artifacts stay quiet unless reviewing. Keep the same artifactId when revising so source updates preserve the user's placement and size. Explain and compare may use Visual Explorer's infographic/comprehension structure. When reviewing or delivering an actual page design, preserve the target product UI, its page background, and real local interactions; do not wrap the page in an explanatory card. Inspect must faithfully render the supplied HTML at the requested viewport without redesign or extra labels; page requests 1200×800 for inspect, while explicit dimensions request an exact mobile or other test viewport. Use Widget intent inspect only with capture:true for one ephemeral viewport render when pixels are needed before delivery; it creates no Canvas object. Prefer one meaningful interaction over decorative controls. Widget buttons reach the client only when explicitly opted into the pull inbox with data-penecho-action="choose" and a bounded data-penecho-prompt; otherwise they are ordinary local Widget behavior, not MCP callbacks. Read and acknowledge inbox messages explicitly; no click or read automatically wakes a stopped client.`;

// Session start repeats only the compact operational reminder, not design text.
const SESSION_INSTRUCTIONS = WORKSPACE_INSTRUCTIONS;

function visualExplorerPrompt() {
  return `${getAuthoringGuidance("visual-explorer", "full").document}\n\n## External MCP delivery\n${SESSION_INSTRUCTIONS}\n\n${MCP_PRESENTATION_INSTRUCTIONS}\n\nCreate responsive HTML/CSS/SVG with minimal JavaScript and present it with penecho_present_widget. For simple native nodes/text use penecho_draw; for bare functions use penecho_plot. Use only tools advertised by this MCP server. Read feedback before replacing an existing artifact; preserve its identity and user placement. Inspect a bounded capture after initial authoring or meaningful layout revisions when visual evidence is needed; correct concrete readability, clipping, and responsive defects. Never claim visual verification without returned pixels.`;
}

const GUIDANCE_VERSION = "2";
const PUBLIC_INSTRUCTIONS = "Use a stable sessionKey per conversation; retain sessionId/documentId. Never switch documents implicitly. Read virtual source before patching with contentHash and requestId; unknown outcomes need identical retries, conflicts need a fresh read. Use baseRevision for geometry edits. Capture only unresolved visual evidence; never show hidden content implicitly. Inbox message/feedback cursors are independent; reading never acknowledges or wakes a model. Prefer mutation completion for status/handled IDs; mark done only after success. Use present_widget for interactive HTML, draw for native marks, plot for functions. Load penecho_get_guidance on demand; reuse unchanged versions. Finish when correct, readable and usable.";

module.exports = { PUBLIC_INSTRUCTIONS, GUIDANCE_VERSION, INVOCATION_INSTRUCTIONS, PAGE_PREVIEW_INSTRUCTIONS, MCP_PRESENTATION_INSTRUCTIONS, WORKSPACE_INSTRUCTIONS, VISUAL_INSTRUCTIONS, VISUAL_TOOL_INSTRUCTIONS, SESSION_INSTRUCTIONS, visualExplorerPrompt };
